openapi: 3.0.4
info:
  title: EIP Api
  version: v1
servers:
  - url: http://localhost:{port}
    description: Local URL
    variables:
      port:
        default: "8080"
paths:
  /input:
    get:
      summary: Get all users
      operationId: getUsers
      security:
        - keycloak: [ "rw_access" ]
      responses:
        "200":
          description: All users
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Users"
    post:
      summary: Add a user
      operationId: postUser
      requestBody:
        description: User names
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/CreateUser"
      security:
        - keycloak: [ "rw_access" ]
      responses:
        "201":
          description: Created
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        done:
          type: boolean
    Users:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: "#/components/schemas/User"
    CreateUser:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
      required:
        - firstName
        - lastName
  securitySchemes:
    keycloak:
      type: openIdConnect
      openIdConnectUrl: http://localhost:18080/realms/eip-test/.well-known/openid-configuration