openapi: 3.0.4
info:
  title: EIP Api
  version: v1
servers:
  - url: http://localhost:{port}
    description: Local URL
    variables:
      port:
        default: "8080"
paths:
  /oneendpoint:
    get:
      summary: One ex
      operationId: all
      responses:
        "200":
          description: All
          content:
            "application/json":
              schema:
                type: string
                example: pong