spring:
  application:
    name: eip-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/eip
    username: app_owner
    password: passmain
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS512
          issuer-uri: http://localhost:18080/realms/eip-test/
          jwk-set-uri: http://localhost:18080/realms/eip-test/protocol/openid-connect/certs
